name = "midnight-media-studio"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "midnight-media-db"
database_id = "87011006-14a4-4f84-83b7-4f3a97f4194a"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "midnight-media-storage"
preview_bucket_name = "midnight-media-storage-preview"

[vars]
# Add your environment variables here
NEXT_PUBLIC_SITE_URL = "https://midnight-media-studio.pages.dev"
